### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by ObserverOfTime** [flurie/tree-sitter-jq#1]
The following features are currently missing from the grammar:

#### [String interpolation](https://stedolan.github.io/jq/manual/#Stringinterpolation-%5C%28foo%29)

```jq
"The input was \(.), which is one less than \(.+1)"
```

#### [Destructuring Alternative Operator](https://stedolan.github.io/jq/manual/#DestructuringAlternativeOperator:?//)

```jq
.[] as {$a, $b, c: {$d, $e}} ?// {$a, $b, c: [{$d, $e}]} | {$a, $b, $d, $e}
```

**Comment by ObserverOfTime** [comment]
Object destructuring doesn't seem to be working properly either:

```jq
. as {$a, $b}
```

**Comment by flurie** [comment]
Hi, thanks for opening the issue. All your examples should be working as intended now. Please let me know if you see anything else.
